config/routes.rb
Rails.application.routes.draw do

  root             'posts#index'

  get 'about'   => 'static_pages#about'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

  get 'signup'  => 'users#new'

  resources :posts do
    resources :images do
      resources :comments, module: :images, :only => [:create, :destroy]
      member do
        post 'make_like'
        delete 'make_unlike'
      end
    end
    member do
      post 'make_like'
      delete 'make_unlike'
    end
    resources :comments, module: :posts, :only => [:create, :destroy]
  end
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  belongs_to :user
  validates :title, presence: true, uniqueness: true 
  validates :slide, presence: { message:"Please choose PDF file before attempting to create post" }
  has_many :comments, as: :host, dependent: :destroy
  has_many :likes, as: :host, dependent: :destroy
  has_many :images, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  
  mount_uploader :slide, SlideUploader

  friendly_id :title, use: :slugged

end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_host

  private

    def set_host
      @host = Post.friendly.find(params[:post_id])
    end
end

app/controllers/posts/like_controller.rb
class Posts::LikeController < LikeController
  before_action :set_host

  private

    def set_host
      @host = Post.friendly.find(params[:post_id])
    end
end

app/controllers/posts/likes_controller.rb
class Posts::LikeController < LikesController
  before_action :set_host

  private

    def set_host
      @host = Post.friendly.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include PostsHelper
  before_action :set_post, only: [:show, :edit, :update, :destroy, :make_like, :make_unlike]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id=current_user.id
    if @post.save
      redirect_to @post, notice: "#{@post.title} was successfully uploaded."
      pdf=File.open("#{Rails.root}/public"+"#{@post.slide}", 'rb').read
      pdf=Magick::Image::from_blob(pdf) do
        self.format = 'PDF'
        self.quality = 100
        self.density = 200
      end
      i=0
      pdf.each do |page|
        i=i+1
        page.format='JPG'
        page.to_blob
        show_path="#{@post.slide}"+sprintf("%02d", i).to_s+".jpg"
        save_path="#{Rails.root}/public"+show_path
        jpg=page.write(save_path)
        @image = @post.images.new(number: i, preview: show_path)
        @image.save
      end
     else
      render :new
     end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    FileUtils.rm_rf("public/uploads/post/slide/#{@post.id}")
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def make_like
    like = @post.likes.new(user_id: current_user.id)
    like.save
    redirect_to(:back)
  end

  def make_unlike
    like = @post.likes.where(user_id: current_user.id).last
    if like==nil or like==[] then redirect_to :back end
    like.delete
    redirect_to(:back)
  end

  def index_images
    images_path=Array.new
    images_names=Dir.entries("public/uploads/post/slide/#{@post.id}").select {|f| !File.directory? f}
    images_names.sort!
    images_names[1..-1].each do |imageName|
      images_path.push("/uploads/post/slide/#{@post.id}/#{imageName}")
    end
    return images_path
  end

  helper_method :index_images 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :text, :slide)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post, html: {multipart: true} do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
      <% if message.include? "Slide" then message=message[5..message.size] end %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :text, class: 'form-control', placeholder: "Write a description..." %>
  </div>
  <div class="field">
    <%= f.label :pdf %><br>
    <%= f.file_field :slide, class: "panel panel-default" %>
  </div>
  <div class="actions">
    <%= f.button raw("Upload"), class: "btn btn-success", data: {disable_with: "<i class='glyphicon glyphicon-repeat fa-spin'></i> Uploading.."} %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Back', @post %>

app/views/posts/index.html.erb
<br>
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />

<div><%= link_to "New Document", new_post_path, class: "btn btn-primary" %></div>

<% if(@posts.count==0) %>
<div class="glyphicon glyphicon-send"><p>no posts uploaded yet start now<p>
</div>
<% end %>

<br />
<br />
<center><table class="table" align="center">

  <tbody>

    <% @posts.each do |post| %>
      
        <tr>
        <%if post.slide.file != nil and post.slide.file.extension=="pdf"%>
        <div class="size"><%=image_tag "/uploads/post/slide/#{post.id}/#{post.slide_identifier}"+"01.jpg" %> <%end%>
          <h1 style="text-align:center;"><%= post.title %></h1>
        <div>
            <%= pluralize(post.likes.count, "like") %>
             <% if post.likes.where(user_id: current_user.id)==[]%>
             <%= link_to raw("<span class='glyphicon glyphicon-thumbs-up'></span> Like"), make_like_post_path(post), method: :post, data: {disable_with: raw("<span class='glyphicon glyphicon-thumbs-down'></span> Unlike")} %>
             <% else %>
             <%= link_to raw("<span class='glyphicon glyphicon-thumbs-down'></span> Unlike"), make_unlike_post_path(post), method: :delete, data: {disable_with: raw("<span class='glyphicon glyphicon-thumbs-up'></span> Like")} %>
             <% end %>
           </div>
        <div><%= link_to raw("<span class='glyphicon glyphicon-download-alt'></span> Download Document"), post.slide_url %></div>
        <div>Uploaded By <%= User.find(post.user_id).name %></div>
        
        
        <% if post.user_id == current_user.id or current_user.admin %>
        <tr><%= link_to "Show", post, class: "btn btn-info", style: "width:50%;" %></tr>
        <tr><%= link_to "Delete",  post, method: :delete, class: "btn btn-danger", style: "width:50%;", confirm: "Are you sure that you wish to delete #{post.title}?" %></tr>
        <% else %>
        <%= link_to "Show", post, class: "btn btn-info", style: "width:100%;" %>
        <% end %>
        </br></br>
      <% post.comments.each do |comment| %><div class="comment">
        <% commenter=User.find_by_id(comment.user_id) %>
        <% if commenter.admin %>
          <%= image_tag("/assets/icon-admin.png", size: "50") %>
        <% else %>
          <%= image_tag("/assets/icon-user.png", size: "50") %>
        <% end %>
        <p class="badge"><%= commenter.name %></p>
        <p class="well"><%= comment.text %></p>
        <p><%= time_ago_in_words comment.created_at %> ago </p>
        <% if commenter == current_user or current_user.admin %>
        <p><%= link_to "delete", [post,comment], method: :delete, data: { confirm: "You sure?" } %></P>
        <% end %>
        </div><% end %>


          <%= form_for [post , post.comments.build] do |f| %>
          <p> <%= f.text_area :text, :size => '40x10', class: "form-control", style: "width:100%;", placeholder: "Write a comment..." %> </p>
          <p> <%= f.submit "post comment", class: "btn btn-primary", style: "width:100%;", data: {disable_with:"post comment"}%> </p>
          <% end %>
          </tr>
        </br></br>
        <div class="line">.</div>
      </br></br>
    <% end %>

    </tbody>
</table></center>

<% will_paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path, class: "btn btn-default" %>

app/views/posts/show.html.erb
<% if !flash[:notice].blank? %>
<p id="notice"><div class="alert alert-success"><%= notice %></div></p>
<% end %>
<ul class="nav nav-tabs">
<li class="active"><%= link_to 'Show All', @post %></li>
<% @post.images.all.each do |image| %>
<li><%= link_to 'page '+image.number.to_s, "/posts/"+@post.title.parameterize+"/images/"+image.number.to_s %></li>
<% end %>
</ul>
<p>
	<% images_path=index_images %>
	<% images_path=images_path.paginate(:page => params[:page]) %>
	<% i=1 %>
	<% images_path.each do |thumbnail| %>
	<div class="size2">
	<%= link_to image_tag(thumbnail), "/posts/"+@post.slug+"/images/"+i.to_s %>
	<% i=i+1 %>
	</div>
	<% end %>  

</p>

<h1><strong><%= @post.title %></strong></h1>

<p>
  <%= @post.text %>
</p>
<%= pluralize(@post.likes.count, "like") %>
<% if @post.likes.where(user_id: current_user.id)==[]%>
<tr><%= link_to raw("<span class='glyphicon glyphicon-thumbs-up'></span> Like"), make_like_post_path(@post), method: :post, data: {disable_with: raw("<span class='glyphicon glyphicon-thumbs-down'></span> Unlike")} %>
<% else %>
<tr> <%= link_to raw("<span class='glyphicon glyphicon-thumbs-down'></span> Unlike"), make_unlike_post_path(@post), method: :delete, data: {disable_with: raw("<span class='glyphicon glyphicon-thumbs-up'></span> Like")} %>
<% end %><br><br>
<%= link_to 'Back', posts_path, class:"btn btn-default" %>

<%= will_paginate images_path %>