config/routes.rb
Rails.application.routes.draw do

  root             'posts#index'

  get 'about'   => 'static_pages#about'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

  get 'signup'  => 'users#new'

  resources :posts do
    resources :images do
      resources :comments, module: :images, :only => [:create, :destroy]
      member do
        post 'make_like'
        delete 'make_unlike'
      end
    end
    member do
      post 'make_like'
      delete 'make_unlike'
    end
    resources :comments, module: :posts, :only => [:create, :destroy]
  end
  

end

app/models/image.rb
class Image < ActiveRecord::Base
	extend FriendlyId
	belongs_to :post
	has_many :comments, as: :host, dependent: :destroy
	has_many :likes, as: :host, dependent: :destroy
	default_scope -> { order(number: :asc) }

	friendly_id :number, use: :scoped, scope: :post
end

app/controllers/images/comments_controller.rb
class Images::CommentsController < CommentsController
  before_action :set_host

  private

    def set_host
      post = Post.friendly.find(params[:post_id])
      @host = post.images.friendly.find(params[:image_id])
    end
end

app/controllers/images/like_controller.rb
class Images::LikeController < LikeController
  before_action :set_host

  private

    def set_host
      post = Post.friendly.find(params[:post_id])
      @host = post.images.friendly.find(params[:image_id])
    end
end

app/controllers/images/likes_controller.rb
class Images::LikeController < LikesController
  before_action :set_host

  private

    def set_host
      post = Post.friendly.find(params[:post_id])
      @host = post.images.friendly.find(params[:image_id])
    end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_post
  before_action :set_image, only: [:show, :edit, :update, :destroy, :make_like, :make_unlike]

  # GET /images
  # GET /images.json
  def index
    @images = @post.images.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = @post.images.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = @post.images.new(image_params)

    respond_to do |format|
      if @image.save
        redirect_to @post.image
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def make_like
    like = @image.likes.new(user_id: current_user.id)
    like.save
    redirect_to(:back)
  end

  def make_unlike
    like = @image.likes.where(user_id: current_user.id).last
    if like==nil or like==[] then redirect_to :back end
    like.delete
    redirect_to(:back)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = @post.images.friendly.find(params[:id])
    end
    def set_post
      @post = Post.friendly.find(params[:post_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:number, :preview)
    end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for(@image) do |f| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>

      <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br>
    <%= f.number_field :number %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form' %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Images</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @images.each do |image| %>
      <tr>
        <td><%= image.id %></td>
        <td><%= image.post_id %></td>
        <td><%= link_to 'Show', image %></td>
        <td><%= link_to 'Edit', edit_image_path(image) %></td>
        <td><%= link_to 'Destroy', image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Image', new_image_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', images_path %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>
<ul class="nav nav-tabs">
<li><%= link_to 'Show All', @post %></li>
<% @post.images.all.each do |image| %>
  <% if image == @image %><li class="active">
  <% else %><li><% end %>
  <%= link_to 'page '+image.number.to_s, "/posts/"+@post.title.parameterize+"/images/"+image.number.to_s %></li>
<% end %>
</ul>
  
</br></br>


<div class="container2">

<div class="right"><% if Image.exists?(Image.find_by_id(@image.id+1)) %>
	<a href='<%=@image.number+1%>'>&rsaquo;</a>
<%end%></div>	
<div class="clear"></div>
<div class="left"><% if @image.number>1 %>
	<a href='<%=@image.number-1%>'>&lsaquo;</a>
<% end %></div>

<div class="center"><%= image_tag @image.preview %></div>

</div>
 
</br>
<span style="float:right;"><%= link_to raw("<span class='glyphicon glyphicon-download-alt'></span> Download Image"), @image.preview %></span>
<span style="float:left;"><%= pluralize(@image.likes.count, "like") %>
<% if @image.likes.where(user_id: current_user.id)==[]%>
<tr><%= link_to raw("<span class='glyphicon glyphicon-thumbs-up'></span> Like"), make_like_post_image_path, method: :post, data: {disable_with: raw("<span class='glyphicon glyphicon-thumbs-down'></span> Unlike")} %>
<% else %>
<tr> <%= link_to raw("<span class='glyphicon glyphicon-thumbs-down'></span> Unlike"), make_unlike_post_image_path, method: :delete, data: {disable_with: raw("<span class='glyphicon glyphicon-thumbs-up'></span> Like")} %>
<% end %></span></br>
<% @image.comments.each do |comment| %><div class="container"><div class="jumbotron">
<% commenter=User.find_by_id(comment.user_id) %>
  <% if commenter.admin %>
  <%= image_tag("/assets/icon-admin.png", size: "50") %>
  <% else %>
  <%= image_tag("/assets/icon-user.png", size: "50") %>
  <% end %>
  <p class="badge"><%= commenter.name %></p>
  <p class="well"><%= comment.text %></p>
  <p><%= time_ago_in_words comment.created_at %> ago </p>
  <% if commenter == current_user or current_user.admin %>
  <p><%= link_to "Delete comment" ,[@post,@image,comment] ,:method => :delete , :confirm => "Are you sure"%></p>
  <% end %>
  </div></div><% end %>
  
  

<div class="container2"><%= form_for [@post, @image, @image.comments.build] do |f| %>
<p> <%= f.text_area :text, class: "form-control", style: "height:100px;width:97%;float:right;", placeholder: "Write a comment..." %> </p>
<p> <%= f.submit "post comment", class: "btn btn-primary", style: "width:97%;float:right;", data: {disable_with:"post comment"}%> </p>
<% end %></div></div></div>