config/routes.rb
Rails.application.routes.draw do

  root             'posts#index'

  get 'about'   => 'static_pages#about'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users

  get 'signup'  => 'users#new'

  resources :posts do
    resources :images do
      resources :comments, module: :images, :only => [:create, :destroy]
      member do
        post 'make_like'
        delete 'make_unlike'
      end
    end
    member do
      post 'make_like'
      delete 'make_unlike'
    end
    resources :comments, module: :posts, :only => [:create, :destroy]
  end
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small style="float:left;padding-top:8px;">
    <p>PDF Converter</p>
  </small>
  <nav>
    <ul>
      <ul style="float:right;position:relative;"><%= link_to "About",   about_path %></ul>
      <ul style="float:right;margin-left:10%;"><a href="https://github.com/AUEzzat/blogger-pdf-converter">Source</a></ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

    <%= link_to raw("<span class='glyphicon glyphicon-home'></span> PDF Converter"), root_path, id: "logo", data: { no_turbolink: true } %>
    <nav>
      <ul class="nav navbar-nav navbar-right" style="position: static;">
        <% if logged_in? %>
          <li>
          <span><%= link_to (raw("<span class='glyphicon glyphicon-user'></span> Logged in as ")+current_user.name), user_path(current_user), class: "label label-success" %></span>
          <% if current_user.admin %>
          <span><%= link_to (raw("<span class= 'glyphicon glyphicon-wrench'></span><span class= 'glyphicon glyphicon-user'></span> Edit users")), users_path, class: "label label-info" %></span>
          <% end %>
          <span><%= link_to (raw("<span class= 'glyphicon glyphicon-log-out'></span> Log out")), logout_path, class: "label label-primary", method: "delete" %></span>
          </li>
        <% else %>
          <li><span><%= link_to (raw("<span class= 'glyphicon glyphicon-log-in'></span> Log in")), login_path, class: "label label-primary" %></span></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>